import { and, asc, desc, eq, gte, lte } from "drizzle-orm";
import { db } from "../../../db";
import { financeJournal } from "../schemas/finance.schema";
import { FinanceType, FinanceCategory, CreateFinanceInput, ListFinanceParams, UpdateFinanceInput, CreateFinanceParam } from "../types";
import { FinanceJournal, mapToFinanceJournal, mapToFinanceJournals } from "../entities/finance.entity";
import { C } from "drizzle-kit/index-BAUrj6Ib";

export const FinanceRepository = {
  async list(params: ListFinanceParams = {}): Promise<FinanceJournal[]> {
    const { type, category, referenceId, minAmount, maxAmount, startDate, endDate, direction = "desc" } = params;

    const where = [] as any[];
    if (type) where.push(eq(financeJournal.type, type));
    if (category) where.push(eq(financeJournal.category, category));
    if (typeof referenceId === "number") where.push(eq(financeJournal.referenceId, referenceId));
    if (typeof minAmount === "number") where.push(gte(financeJournal.amount, String(minAmount)));
    if (typeof maxAmount === "number") where.push(lte(financeJournal.amount, String(maxAmount)));
    if (startDate) where.push(gte(financeJournal.createdAt, startDate));
    if (endDate) where.push(lte(financeJournal.createdAt, endDate));

    const orderCol = financeJournal.createdAt;

    // Map DB results to FinanceJournal entities
    const rows = await db
      .select()
      .from(financeJournal)
      .where(where.length ? (where.length === 1 ? where[0] : and(...where)) : undefined)
      .orderBy(direction === "asc" ? asc(orderCol) : desc(orderCol));

    return mapToFinanceJournals(rows);
  },

  async get(id: number): Promise<FinanceJournal | undefined> {
    const rows = await db.select().from(financeJournal).where(eq(financeJournal.id, id)).limit(1);
    return rows.length > 0 ? mapToFinanceJournal(rows[0]) : undefined;
  },

  async getDailyFinanceSummary(startDate: Date, endDate: Date): Promise<FinanceJournal[]> {
    const rows = await db
      .select()
      .from(financeJournal)
      .where(
        and(
          gte(financeJournal.createdAt, startDate),
          lte(financeJournal.createdAt, endDate)
        )
      )
      .orderBy(asc(financeJournal.category));

    return mapToFinanceJournals(rows);
  },

  async create(data: CreateFinanceParam): Promise<number> {
    // TODO: Check mapping for category with type
    const newData: CreateFinanceInput = {
      type: data.type as FinanceType,
      amount: String(data.amount), // DB expects string
      category: data.category as FinanceCategory,
      referenceId: data.referenceId ?? null,
      description: data.description ?? null,
      // id and createdAt are auto-generated by DB
    };
    const res = await db.insert(financeJournal).values(newData);
    const resultObj: any = Array.isArray(res) ? res[0] : res;
    const insertId = resultObj?.insertId as number | undefined;
    if (typeof insertId === "number") return insertId;
    throw new Error("Insert succeeded but insertId was not returned by the driver");
  },

  async update(id: number, data: Partial<CreateFinanceParam>): Promise<boolean> {
    // const updateData: UpdateFinanceInput = {};
    // if (data.type !== undefined) updateData.type = data.type as FinanceType;
    // if (data.amount !== undefined) updateData.amount = String(data.amount);
    // if (data.category !== undefined) updateData.category = data.category as FinanceCategory;
    // if (data.referenceId !== undefined) updateData.referenceId = data.referenceId;
    // if (data.description !== undefined) updateData.description = data.description;

    // TODO: Check mapping for category with type
    const res = await db
      .update(financeJournal)
      .set(data as Partial<CreateFinanceInput>)
      .where(eq(financeJournal.id, id));
    const resultObj: any = Array.isArray(res) ? res[0] : res;
    const affectedRows = resultObj?.affectedRows ?? resultObj?.rowsAffected;
    return (affectedRows ?? 0) > 0;
  },

  async remove(id: number): Promise<boolean> {
    const res = await db.delete(financeJournal).where(eq(financeJournal.id, id));
    const resultObj: any = Array.isArray(res) ? res[0] : res;
    const affectedRows = resultObj?.affectedRows ?? resultObj?.rowsAffected;
    return (affectedRows ?? 0) > 0;
  },
};

